### ISSUE TITLE
Implement test for the no existing pandas versions of the functions

### ISSUE THREAD

**Issue by ggsdc** [baobabsoluciones/mango#63]
Some functions have an automatic check to see if pandas is installed or not.
Unit tests should take into account this check as well.
We should see if we can mock that the library is not installed.

**Comment by AntonioGonzalezSuarez** [comment]
We can. Take a look at aemet tests but this should work

```python
from unittest import TestCase, mock
def foo():
    try:
        import pandas as pd
    except ImportError as e:
        raise ImportError("pandas needs to be installed") from e
class Test(TestCase):
    def test_pandas_not_installed(self):
        with mock.patch.dict("sys.modules", {"pandas": None}):
            self.assertRaises(
                ImportError,
                foo,
            )
```

**Comment by ggsdc** [comment]
> We can. Take a look at aemet tests but this should work
> 
> ```python
> from unittest import TestCase, mock
> def foo():
>     try:
>         import pandas as pd
>     except ImportError as e:
>         raise ImportError("pandas needs to be installed") from e
> class Test(TestCase):
>     def test_pandas_not_installed(self):
>         with mock.patch.dict("sys.modules", {"pandas": None}):
>             self.assertRaises(
>                 ImportError,
>                 foo,
>             )
> ```

Ok, perfect, that way we could test both versions of a method
